<?php

########################################################################
# Extension Manager/Repository config file for ext: "justimmo"
#
# Auto generated by Extension Builder 2012-03-07
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'justimmo.at Real estate plugin',
	'description' => 'Allows querying the justimmo.at API. It provides a search interface, list and detail view.',
	'category' => 'plugin',
	'author' => 'Thomas Juhnke',
	'author_email' => 'tommy@van-tomas.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3.0',
			'fluid' => '1.3.0',
			'static_info_tables' => '2.3.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>